// Automatically generated by astro-icon
// bbf2e1f1b094cf0cbddc7f21f8573d4bff8875d364e719fce19a41ffa4e8a3c9

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "social/facebook"
		| "social/instagram"
		| "social/twitter";
}